### ISSUE TITLE
macro `offset!()` is not in prelude

### ISSUE THREAD

**Issue by lum1narie** [mrclean71774/scad_tree#2]
[`offset!()`](https://github.com/mrclean71774/scad_tree/blob/00a694874b2c02234d68d168c7bd14320f16c018/scad_tree/src/scad.rs#L3074) is not included in [`prelude`](https://github.com/mrclean71774/scad_tree/blob/00a694874b2c02234d68d168c7bd14320f16c018/scad_tree/src/lib.rs#L44).
I assume this wasn't intentional.

**Comment by mrclean71774** [comment]
Yes, that was an oversight on my part. Fixed in version 4.1. Thank you very much.
